### ISSUE TITLE
Add *.sqlproj Files to SortProjectItems

### ISSUE THREAD

**Issue by chadboettcher** [KirillOsenkov/CodeCleanupTools#13]
Hello,

Would it be possible to add *.sqlproj projects to the SortProjectItems tool to sort the SQL files in a project, just like the C# and VB files?

Thanks,

Chad

**Comment by KirillOsenkov** [comment]
Yeah, you should just add a line here:
https://github.com/KirillOsenkov/CodeCleanupTools/blob/master/SortProjectItems/SortProjectItems.cs#L29

Would you like to submit a PR?

**Comment by chadboettcher** [comment]
Thanks.  I did download the code and made the simple change.  I was thinking in terms of the https://chocolatey.org/ install but I skipped over that whole thing and just built the exe locally.  Thanks for a great tool.
