### ISSUE TITLE
build errors with latest updates

### ISSUE THREAD

**Issue by korygill** [KirillOsenkov/CodeCleanupTools#5]
Need to update csproj for both FormatSolution and MoveUsings to add
    `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>`

at bottom of first `PropertyGroup`

**Comment by KirillOsenkov** [comment]
Fixed, thanks!

**Comment by KirillOsenkov** [comment]
Also fixed the packages.config files.
