### ISSUE TITLE
MoveUsings adds UTF-8 BOM for files without BOM.

### ISSUE THREAD

**Issue by ghost** [KirillOsenkov/CodeCleanupTools#8]
As the descriptions says, the UTF-8 BOM is added on save.
See: [File.WriteAllText(filePath, text, Encoding.UTF8)](https://github.com/KirillOsenkov/CodeCleanupTools/blob/master/MoveUsings/MoveUsings.cs#L33) I guess it would better to check the presence first and then save the file according to the finding.

**Comment by KirillOsenkov** [comment]
Thanks. I've standardized on no BOM anywhere. The consensus is that BOM is not needed/helpful. I've updated all the tools to not write the BOM but forgot about MoveUsings.

This is now fixed. Thanks!
